### ISSUE TITLE
Big Loses Froggy to Gamma Wrong Soundbank?

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx-sound-overhaul#1]
I noticed that the cutscene where Gamma swipes Froggy from Big might be using the wrong soundbank file. The sound effects that play are not from the soundbank for Big's cutscene. It seems like it might be using the bank intended for the cutscene where Knuckles restores most of the Master Emerald. This might be incorrect on Dreamcast, too.

**Comment by PiKeyAr** [comment]
Since you have looked into it, which is the soundbank that plays during the cutscene and which do you think should be the correct one?

**Comment by supercoolsonic** [comment]
E_0091 is the one I believe it's using, and I think it should be using E_00D4 instead.

**Comment by PiKeyAr** [comment]
Should be fixed now
[SoundOverhaul.zip](https://github.com/PiKeyAr/sadx-sound-overhaul/files/3488481/SoundOverhaul.zip)

**Comment by supercoolsonic** [comment]
Indeed, it's using the other soundbank. ...To be perfectly honest, neither sounds incorrect. I brought this up because the cutscene was using sounds that weren't in the soundbank that was apparently made for it. I'm not saying it _must_ use bank E_00D4, as other cutscenes in the game borrow soundbanks from other cutscenes, but it seemed strange to me that this one had a bank with the same name as it, yet wasn't using it. I should reiterate, on Dreamcast, the cutscene uses the soundbank it was using before, not this one. Up to you if you want to keep it this way, but I'm kinda leaning on leaving it as it is now.

**Comment by PiKeyAr** [comment]
Looking at the sound files in E_0091 it does seem that it isn't meant to be used with that cutscene as it has a lot of other emerald-related sounds. E_00D4, on the other hand, has Gamma's hover sound, which also plays on the DC in that cutscene, and one unused sound. And the soundbank immediately afterwards is Big's pre-Chaos 6 cutscene. I guess I'll leave it like the original game.

**Comment by supercoolsonic** [comment]
Oh. I could've sworn that it used that *ding* sound on DC, too. Just double-checked, and sure enough, it's supposed to use E_00D4. So it'll stay like it is now?
