### ISSUE TITLE
Sounds mods no longer work after latest update.

### ISSUE THREAD

**Issue by NitroDreams** [PiKeyAr/sadx-sound-overhaul#2]
After updating to the most current version (0.8525), additional sound mods no longer work. The reason likely being the SFX are now in sound banks rather than folders and .WAV. It makes testing sounds a bit more difficult and it breaks other mods that use the previous format.

**Comment by PiKeyAr** [comment]
If mod order isn't an issue it could be that the Mod Loader doesn't prioritize sounds correctly when loading raw folders after DAT soundbanks, which is something I can't fix.

For testing raw sound folders, use the soundbank tools available [here](https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/SoundOverhaul_tools.7z). You can use them to unpack the DAT soundbanks in Sound Overhaul and/or compress the sound folders in the mods you're testing.

While I wish to maintain compatibility where possible, having raw sound folders in place of DAT soundbanks affects load times significantly and it's better to avoid it.
