### ISSUE TITLE
Startup Sounds missing

### ISSUE THREAD

**Issue by Sonicjan** [PiKeyAr/sadx-sound-overhaul#5]
After updating Sound Overhaul 2 to Sound Overhaul 3 through the SADXModManager, the game stopped playing the SEGA and Sonic Team voicelines.

**Comment by PiKeyAr** [comment]
There voices are not part of Sound Overhaul.

**Comment by PiKeyAr** [comment]
To get them back, use either SADXFE or the Dreamcast DLC mod. They're also disabled by default in the new version of the DLC mod.
