### ISSUE TITLE
US Eggman Audio with JP Voices in Sky Deck 2

### ISSUE THREAD

**Issue by RetroForever** [PiKeyAr/sadx-sound-overhaul#8]
recently I've found that even though I have the voice audio set to japanese in my save file and the mod loader, Eggman's lines in Sky Deck Act 2 play in english. I've done a lot of testing and this mod seems like the one that's causing it.
even weirder, in an old video of the PC version modded, Eggman's lines are actually in japanese as they should be. that means this is most likely something that was broken in an update at some point

https://user-images.githubusercontent.com/79285355/199387941-419b8c2d-f8e5-45e1-b412-060a49f84db2.mp4

time stamp for video that shows it worked before:
https://youtu.be/w02BEZWafCg?t=3019

**Comment by PiKeyAr** [comment]
Thanks for the report. This should be fixed in the latest update.
